<a href="https://colab.research.google.com/github/CamFuenzalidaC/super_mercado/blob/main/Actividad_MD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#iportamos librerias
import pandas as pd
import numpy as np

In [ ]:
url = "https://raw.githubusercontent.com/CamFuenzalidaC/super_mercado/main/oasis_live_25.csv"
df = pd.read_csv(url)

In [ ]:
df.head()

,concert_id,date,city,country_or_constituent_country,sovereign_country,venue,residency_key,shows_in_city_residency,attendance_reported_city_residency,attendance_scope_note,attendance_estimated_per_concert,gross_reported_usd_per_concert,avg_ticket_price_usd_pollstar,gross_estimated_usd_per_concert,gross_estimation_note,setlist_variant,setlist,source_tour_dates_attendance_url,source_tour_financials_url,source_setlist_url
0,1,2025-07-04,Cardiff,Wales,United Kingdom,Principality Stadium,cardiff,2,140000,Wikipedia tour-date table reports attendance g...,70000,NaN,181.93,12735185.00,Per-concert grosses were not publicly reported...,cardiff,Song played from tape: Tomorrow Never Knows | ...,https://en.wikipedia.org/wiki/Oasis_Live_'25_Tour,https://news.pollstar.com/2025/12/12/oasis-reu...,https://www.setlist.fm/setlist/oasis/2025/prin...
1,2,2025-07-05,Cardiff,Wales,United Kingdom,Principality Stadium,cardiff,2,140000,Wikipedia tour-date table reports attendance g...,70000,NaN,181.93,12735185.00,Per-concert grosses were not publicly reported...,cardiff,Song played from tape: Tomorrow Never Knows | ...,https://en.wikipedia.org/wiki/Oasis_Live_'25_Tour,https://news.pollstar.com/2025/12/12/oasis-reu...,https://www.setlist.fm/setlist/oasis/2025/prin...
2,3,2025-07-11,Manchester,England,United Kingdom,Heaton Park,manchester,5,370000,Wikipedia tour-date table reports attendance g...,74000,NaN,181.93,13462909.86,Per-concert grosses were not publicly reported...,manchester,Song played from tape: Fuckin' in the Bushes |...,https://en.wikipedia.org/wiki/Oasis_Live_'25_Tour,https://news.pollstar.com/2025/12/12/oasis-reu...,https://www.setlist.fm/setlist/oasis/2025/heat...
3,4,2025-07-12,Manchester,England,United Kingdom,Heaton Park,manchester,5,370000,Wikipedia tour-date table reports attendance g...,74000,NaN,181.93,13462909.86,Per-concert grosses were not publicly reported...,manchester,Song played from tape: Fuckin' in the Bushes |...,https://en.wikipedia.org/wiki/Oasis_Live_'25_Tour,https://news.pollstar.com/2025/12/12/oasis-reu...,https://www.setlist.fm/setlist/oasis/2025/heat...
4,5,2025-07-16,Manchester,England,United Kingdom,Heaton Park,manchester,5,370000,Wikipedia tour-date table reports attendance g...,74000,NaN,181.93,13462909.86,Per-concert grosses were not publicly reported...,manchester,Song played from tape: Fuckin' in the Bushes |...,https://en.wikipedia.org/wiki/Oasis_Live_'25_Tour,https://news.pollstar.com/2025/12/12/oasis-reu...,https://www.setlist.fm/setlist/oasis/2025/heat...

In [ ]:
df.columns #analicis especifico de la columnas

Index(['concert_id', 'date', 'city', 'country_or_constituent_country',
       'sovereign_country', 'venue', 'residency_key',
       'shows_in_city_residency', 'attendance_reported_city_residency',
       'attendance_scope_note', 'attendance_estimated_per_concert',
       'gross_reported_usd_per_concert', 'avg_ticket_price_usd_pollstar',
       'gross_estimated_usd_per_concert', 'gross_estimation_note',
       'setlist_variant', 'setlist', 'source_tour_dates_attendance_url',
       'source_tour_financials_url', 'source_setlist_url'],
      dtype='object')

In [ ]:
df['city'].value_counts() # variables categoricas encontradas: obejetivo city

city
London             7
Manchester         5
Edinburgh          3
Melbourne          3
Cardiff            2
Toronto            2
East Rutherford    2
Pasadena           2
Dublin             2
São Paulo          2
Mexico City        2
Tokyo              2
Sydney             2
Buenos Aires       2
Chicago            1
Goyang             1
Santiago           1
Name: count, dtype: int64

In [ ]:
df['city'].value_counts().count() #cuantas filas tiene la variable city

np.int64(17)

In [ ]:
df['city'].unique() #extrar los datos unicos de city

array(['Cardiff', 'Manchester', 'London', 'Edinburgh', 'Dublin',
       'Toronto', 'Chicago', 'East Rutherford', 'Pasadena', 'Mexico City',
       'Goyang', 'Tokyo', 'Melbourne', 'Sydney', 'Buenos Aires',
       'Santiago', 'São Paulo'], dtype=object)

In [ ]:
df.isnull().sum() # variables nulas

concert_id                             0
date                                   0
city                                   0
country_or_constituent_country         0
sovereign_country                      0
venue                                  0
residency_key                          0
shows_in_city_residency                0
attendance_reported_city_residency     0
attendance_scope_note                  0
attendance_estimated_per_concert       0
gross_reported_usd_per_concert        41
avg_ticket_price_usd_pollstar          0
gross_estimated_usd_per_concert        0
gross_estimation_note                  0
setlist_variant                        0
setlist                                0
source_tour_dates_attendance_url       0
source_tour_financials_url             0
source_setlist_url                     0
dtype: int64

In [ ]:
df.isnull().sum()

concert_id                             0
date                                   0
city                                   0
country_or_constituent_country         0
sovereign_country                      0
venue                                  0
residency_key                          0
shows_in_city_residency                0
attendance_reported_city_residency     0
attendance_scope_note                  0
attendance_estimated_per_concert       0
gross_reported_usd_per_concert        41
avg_ticket_price_usd_pollstar          0
gross_estimated_usd_per_concert        0
gross_estimation_note                  0
setlist_variant                        0
setlist                                0
source_tour_dates_attendance_url       0
source_tour_financials_url             0
source_setlist_url                     0
dtype: int64

In [ ]:
#ponevariable estadisticas en forma numerica
df.describe().round()

,concert_id,shows_in_city_residency,attendance_reported_city_residency,attendance_estimated_per_concert,gross_reported_usd_per_concert,avg_ticket_price_usd_pollstar,gross_estimated_usd_per_concert
count,41.0,41.0,41.0,41.0,0.0,41.0,41.0
mean,21.0,3.0,202537.0,70244.0,NaN,182.0,12779558.0
std,12.0,1.0,112741.0,10945.0,NaN,0.0,1991204.0
min,1.0,1.0,52000.0,50000.0,NaN,182.0,9096561.0
25%,11.0,2.0,130000.0,60000.0,NaN,182.0,10915873.0
50%,21.0,2.0,162000.0,70000.0,NaN,182.0,12735185.0
75%,31.0,3.0,210000.0,81000.0,NaN,182.0,14736428.0
max,41.0,5.0,405000.0,90000.0,NaN,182.0,16373809.0

In [ ]:
df.info() #muestras los tispos de datos y nulos de la dt

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 20 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   concert_id                          41 non-null     int64
 1   date                                41 non-null     object
 2   city                                41 non-null     object
 3   country_or_constituent_country      41 non-null     object
 4   sovereign_country                   41 non-null     object
 5   venue                               41 non-null     object
 6   residency_key                       41 non-null     object
 7   shows_in_city_residency             41 non-null     int64
 8   attendance_reported_city_residency  41 non-null     int64
 9   attendance_scope_note               41 non-null     object
 10  attendance_estimated_per_concert    41 non-null     int64
 11  gross_reported_usd_per_concert      0 non-null      float64
 12  avg_ticket_price_usd_pollstar       41 non-null     float64
 13  gross_estimated_usd_per_concert     41 non-null     float64
 14  gross_estimation_note               41 non-null     object
 15  setlist_variant                     41 non-null     object
 16  setlist                             41 non-null     object
 17  source_tour_dates_attendance_url    41 non-null     object
 18  source_tour_financials_url          41 non-null     object
 19  source_setlist_url                  41 non-null     object
dtypes: float64(3), int64(4), object(13)
memory usage: 6.5+ KB

In [ ]:
df.shape # ver las dimensiones

(41, 20)

In [ ]:
df_limpio= df.dropna() #elimina los valores nulos

In [ ]:
df_limpio.to_csv("nuevo_csv_lmpio.csv")